Programming_Practice/Python/Web_Django/Web_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Web_Django.views import HomeView
from Web_Django.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmarkApp.urls', namespace='bookmark')),
    path('blog/', include('blogApp.urls', namespace='blog')),
    path('photo/', include('photoApp.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Programming_Practice/Python/Web_Django/blogApp/urls.py
from django.urls import path
from blogApp.views import *

app_name = 'blogApp'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>', PostDV.as_view(), name='post_detail'),

    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(month_format='%m'), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(month_format='%m'), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
]

Programming_Practice/Python/Web_Django/bookmarkApp/urls.py
from django.urls import path
from bookmarkApp.views import *

app_name = 'bookmarkApp'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),

    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

Programming_Practice/Python/Web_Django/photoApp/urls.py
from django.urls import path
from .views import AlbumLV, AlbumDV, PhotoDV
from .views import AlbumPhotoCV, AlbumChangeLV, AlbumPhotoUV, AlbumDeleteView
from .views import PhotoCreateView, PhotoChangeLV, PhotoUpdateView, PhotoDeleteView

app_name = 'photoApp'

urlpatterns = [
    path('', AlbumLV.as_view(), name='index'),
    path('album/', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
    path('photo/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUpdateView().as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView().as_view(), name='photo_delete'),
]

Programming_Practice/Python/Web_Django/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Web Programming{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}?ver=2" />
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"/>#}
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"/>#}
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

{#    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.js"></script>#}
</head>

<body>
    <div id="header">
        <h2 class="maintitle">Easy &amp; Fast Django Web Programming</h2>
{#        <h4 class="welcome">Welcome, <a href="#">shkim</a> /#}
{#            <a href="#">Change Password</a> /#}
{#            <a href="#">Logout</a>#}
{#        </h4>#}
        {% if user.is_active %}
            <h4 class="welcome">Welcome, /
                <strong>{% firstof user.get_short_name user.get_user_name %}</strong>
                <a href="{% url 'password_change' %}">Change Password</a> /
                <a href="{% url 'logout' %}">Logout</a>
            </h4>
        {% else %}
            <h4 class="welcome">Welcome, Anonymous /
                <a href="{% url 'login' %}">Login</a> /
                <a href="{% url 'register' %}">Register</a>
            </h4>
        {% endif %}
    </div>

    <div id="menu">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'bookmarkApp:index' %}">Bookmark</a></li>
        <li><a href="{% url 'blogApp:index' %}">Blog</a></li>
        <li><a href="{% url 'photoApp:index' %}">Photo</a></li>

        <li><a href="#">Add&bigtriangledown;</a>
            <ul>
                <li><a href="{% url 'bookmarkApp:add' %}">Bookmark</a></li>
                <li><a href="{% url 'blogApp:add' %}">Blog</a></li>
                <li><a href="{% url 'photoApp:album_add' %}">Album</a></li>
                <li><a href="{% url 'photoApp:photo_add' %}">Photo</a></li>
            </ul>
        </li>
        <li><a href="#">Change&bigtriangledown;</a>
            <ul>
                <li><a href="{% url 'bookmarkApp:change' %}">Bookmark</a></li>
                <li><a href="{% url 'blogApp:change' %}">Blog</a></li>
                <li><a href="{% url 'photoApp:album_change' %}">Album</a></li>
                <li><a href="{% url 'photoApp:photo_change' %}">Photo</a></li>
            </ul>
        </li>

        <li><a href="{% url 'blogApp:post_archive' %}">Archive</a></li>
        <li><a href="{% url 'blogApp:search' %}">Search</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
    </div>

    {% block content %}{% endblock %} {% block footer %}{% endblock %}
</body>

</html>

Programming_Practice/Python/Web_Django/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% load staticfiles %}
{% block extrastyle %} {% static 'css/home.css' %}{% endblock %}

{% block content %}
<div id="content_home">
    <div id="homeimg">
        <a href="/"><img src="{% static 'image/django_actor_big.jpg' %}" style="height:256px;" alt="Unknown"></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
            <td><strong><i><a href="{% url 'bookmarkApp:index' %}">Bookmark</a></i></strong></td>
            <td>You can store your own bookmarks by Bookmark application. It's also possible to update or delete your bookmarks.</td>
            <td class="Edit"><i><a href="{% url 'bookmarkApp:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'bookmarkApp:change' %}">Change</a></i></td>
        </tr>

        <tr>
            <td><strong><i><a href="{% url 'blogApp:index' %}">Blog</a></i></strong></td>
            <td>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc.</td>
            <td class="Edit"><i><a href="{% url 'blogApp:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'blogApp:change' %}">Change</a></i></td>
        </tr>

        <tr>
            <td><strong><i><a href="#">Photo</a></i></strong></td>
            <td>You can upload your own photos through this application. If you delete an album, all photos within it will be deleted.</td>
            <td class="Edit"><i><a href="{% url 'photoApp:album_add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'photoApp:album_change' %}">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}