Programming_Practice/Python/Web_Django/Web_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Web_Django.views import HomeView
from Web_Django.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmarkApp.urls', namespace='bookmark')),
    path('blog/', include('blogApp.urls', namespace='blog')),
    path('photo/', include('photoApp.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Programming_Practice/Python/Web_Django/blogApp/urls.py
from django.urls import path
from blogApp.views import *

app_name = 'blogApp'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>', PostDV.as_view(), name='post_detail'),

    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(month_format='%m'), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(month_format='%m'), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
]

Programming_Practice/Python/Web_Django/photoApp/urls.py
from django.urls import path
from .views import AlbumLV, AlbumDV, PhotoDV
from .views import AlbumPhotoCV, AlbumChangeLV, AlbumPhotoUV, AlbumDeleteView
from .views import PhotoCreateView, PhotoChangeLV, PhotoUpdateView, PhotoDeleteView

app_name = 'photoApp'

urlpatterns = [
    path('', AlbumLV.as_view(), name='index'),
    path('album/', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
    path('photo/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUpdateView().as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView().as_view(), name='photo_delete'),
]

Programming_Practice/Python/Web_Django/photoApp/models.py
from django.db import models
from django.urls import reverse
from .fields import ThumbnailImageField
from django.contrib.auth.models import User


# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('photoApp:album_detail', args=(self.id, ))


class Photo(models.Model):
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photoApp:photo_detail', args=(self.id, ))

Programming_Practice/Python/Web_Django/photoApp/forms.py
from photoApp.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
                                           fields=['image', 'title', 'description'],
                                           extra=2)

Programming_Practice/Python/Web_Django/photoApp/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album, Photo
from django.urls import reverse_lazy
from Web_Django.views import LoginRequiredMixin
from .forms import PhotoInlineFormSet


# Create your views here.
class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photoApp:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)


class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photoApp/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photoApp:index')


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photoApp:index')


class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photoApp/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)


class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photoApp:index')


class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photoApp/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photoApp/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/album_change_list.html
{% extends 'base.html' %}

{% block title %}album_change_list.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Album Change - {{ user }}</h1>

        <table class="change-list">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.description|linebreaks }}</td>
                        <td>{{ item.owner }}</td>
                        <td><a href="{% url 'photoApp:album_update' item.id %}">Update</a></td>
                        <td><a href="{% url 'photoApp:album_delete' item.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Album Delete</h1>

        <form action="." method="POST"> {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm"/>
        </form>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/album_detail.html
{% extends 'base.html' %}
{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'photo/photo.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h2 style="display: inline">{{ object.name }}</h2>
        &emsp;<strong><i>{{ object.description }}</i></strong>
        <hr/>
        <div class="album-detail">
            {% for photo in object.photo_set.all %}
                <div class="album-detail-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumbnail" src="{{ photo.image.thumb_url }}"/>
                    </a>
                    <li>{{ photo.title }}</li>
                    <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/album_form.html
{% extends 'base.html' %}

{% block title %}album_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'css/forms.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Album-Photo InlineFormSet</h1>

        {% if form.is_multipart or formset.is_multipart %}
            <form enctype="multipart/form-data" method="POST" action=".">
        {% else %}
            <form method="POST" action=".">
        {% endif %}
        {% csrf_token %}

        {% if form.errors %}
            <p class="errornote">Wrong! Please correct the FORM error(s) below.</p>
        {% endif %}
        {% if formset.errors %}
            <p class="errornote">Wrong! Please correct the FORMSET error(s) below.</p>
        {% endif %}

        <h4>Create or Update Album contents.</h4>
        <fieldset class="aligned">
            <div class="form-row">
                {{ form.name.label_tag }} {{ form.name }}
            </div>
            <div class="form-row">
                {{ form.description.label_tag }} {{ form.description }}
            </div>
        </fieldset>

        <h4>Create or Update Photo contents.</h4>

        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.id }}
            <fieldset class="aligned">
                <div class="form-row">
                    {{ form.image.label_tag }} {{ form.image }}
                </div>
                <div class="form-row">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-row">
                    {{ form.description.label_tag }} {{ form.description }}
                </div>
            </fieldset>
        {% endfor %}

        <div class="submit-row">
            <input type="submit" value="Submit"/>
        </div>

        <script type="text/javascript">document.getElementById('id_name').focus()</script>
        </form>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/album_list.html
{% extends 'base.html' %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'photo/photo.css' %}{% endblock %}

{% block content %}
<div id="content">
    {% for item in object_list %}
        <div class="clear_float">
            <h2 style="display: inline"><a href="{% url 'photoApp:album_detail' item.id %}">{{ item.name }}</a></h2>
            &emsp;<strong><i>{{ item.description }}</i></strong>
        </div>
        <hr/>
        <div class="album-list">
            {% for photo in item.photo_set.all|slice:":5" %}
                <div class="album-list-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/photo_change_list.html
{% extends 'base.html' %}

{% block title %}photo_change_list.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Photo Change - {{ user }}</h1>

        <table class="change-list">
            <thead>
                <tr>
                    <th>Album</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                    <tr>
                        <td>{{ item.album }}</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.description }}</td>
                        <td>{{ item.owner }}</td>
                        <td><a href="{% url 'photoApp:photo_update' item.id %}">Update</a></td>
                        <td><a href="{% url 'photoApp:photo_delete' item.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/photo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Photo Delete</h1>

        <form action="." method="POST"> {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm"/>
        </form>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/photo_detail.html
{% extends 'base.html' %}
{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'photo/photo.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h2>{{ object.title }}</h2>

        <table class="photo-detail">
            <tr>
                <td>
                    <a href="{{ object.image.url }}">
                        <img style="max-width: 100%" src="{{ object.image.url }}"/>
                    </a>
                </td>
                <td>
                    <ul>
                        <li>Photo Description</li>
                        {% if object.description %}
                            <p>{{ object.description|linebreaks }}</p>
                        {% else %}
                            <p>(blank)</p>
                        {% endif %}
                        <li>Date Uploaded</li>
                            <p>{{ object.upload_date }}</p>
                        <li>Album Name</li>
                            <p><a href="{% url 'photo:album_detail' object.album_id %}">{{ object.album.name }}</a></p>
                    </ul>
                </td>
            </tr>
        </table>
    </div>
{% endblock %}

Programming_Practice/Python/Web_Django/photoApp/templates/photoApp/photo_form.html
{% extends 'base.html' %}

{% block title %}photo_form.html{% endblock %}

{% block extrastyle %}{% static 'css/forms.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Photo Create/Update - {{ user }}</h1>
        {% if form.is_multipart %}
            <form enctype="multipart/form-data" method="POST" action=".">
        {% else %}
            <form method="POST" action=".">
        {% endif %}
        {% csrf_token %}

        {% if form.errors %}
        <p class="errornote">Wrong! Please correct the error(s) below.</p>
        {% endif %}

        <p>This is a creation or update form for your photo.</p>

        <fieldset class="aligned">
            <div class="form-row">
                {{ form.image.label_tag }} {{ form.image }}
            </div>
            <div class="form-row">
                {{ form.album.label_tag }} {{ form.album }}
                <button type="button"><a href="{% url 'photoApp:album_add' %}">Add Album</a></button>
            </div>
            <div class="form-row">
                {{ form.title.label_tag }} {{ form.title }}
            </div>
            <div class="form-row">
                {{ form.description.label_tag }} {{ form.description }}
            </div>
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="Submit"/>
        </div>

        <script type="text/javascript">document.getElementById('id_album').focus();</script>
        </form>
    </div>
{% endblock %}

{#{% block footer %}#}
{#<div id="footer">#}
{#    &copy; Y.M.Kwon Django Web Programming Since 2019#}
{#</div>#}
{#{% endblock footer %}#}