Programming_Practice/Python/Web_Django/Web_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Web_Django.views import HomeView
from Web_Django.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmarkApp.urls', namespace='bookmark')),
    path('blog/', include('blogApp.urls', namespace='blog')),
    path('photo/', include('photoApp.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Programming_Practice/Python/Web_Django/blogApp/urls.py
from django.urls import path
from blogApp.views import *

app_name = 'blogApp'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>', PostDV.as_view(), name='post_detail'),

    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(month_format='%m'), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(month_format='%m'), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
]

Programming_Practice/Python/Web_Django/bookmarkApp/urls.py
from django.urls import path
from bookmarkApp.views import *

app_name = 'bookmarkApp'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),

    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('change/', BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

Programming_Practice/Python/Web_Django/bookmarkApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

Programming_Practice/Python/Web_Django/bookmarkApp/views.py
from django.shortcuts import render
from bookmarkApp.models import Bookmark
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from Web_Django.views import LoginRequiredMixin

# Create your views here.


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmarkApp:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)


class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmarkApp/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmarkApp:index')


class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmarkApp:index')

Programming_Practice/Python/Web_Django/bookmarkApp/templates/bookmarkApp/bookmark_change_list.html
{% extends 'base.html' %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark Change - {{ user }}</h1>

        <table class="change-list">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Url</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>

            <tbody>
                {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'bookmarkApp:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'bookmarkApp:delete' item.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/bookmarkApp/templates/bookmarkApp/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark Delete</h1>

        <form action="." method="POST">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm"/>
        </form>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/bookmarkApp/templates/bookmarkApp/bookmark_detail.html
{% extends "base.html" %}
{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div id="content">
        <h1>{{ object.title }}</h1>
        <ul>
            <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
        </ul>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/bookmarkApp/templates/bookmarkApp/bookmark_form.html
{% extends 'base.html' %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'css/forms.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark Create/Update - {{ user }}</h1>

        <form action="." method="POST">{% csrf_token %}
            {% if form.errors %}
                <p class="errornote">Wrong! Please correct the error(s) below.</p>
            {% endif %}

            <p>This is a creation or update form for your bookmark.</p>

            <fieldset class="aligned">
                <div class="form-row">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-row">
                    {{ form.url.label_tag }} {{ form.url }}
                </div>
            </fieldset>

            <div class="submit-row">
                <input type="submit" value="Submit"/>
            </div>

            <script type="text/javascript">document.getElementById('id_title').focus()</script>
        </form>
    </div>
{% endblock %}

{% block footer %}
    <div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
    </div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/bookmarkApp/templates/bookmarkApp/bookmark_list.html
{% extends "base.html" %}
    {% block title %}Bookmark List{% endblock %}
{% block content %}
    <div id="content">
        <h1>Bookmark List</h1>
        <ul>
            {% for bookmark_row in object_list %}
                <li><a href="{% url 'bookmarkApp:detail' bookmark_row.id %}">{{ bookmark_row }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}