Programming_Practice/Python/Web_Django/Web_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Web_Django.views import HomeView
from Web_Django.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmarkApp.urls', namespace='bookmark')),
    path('blog/', include('blogApp.urls', namespace='blog')),
    path('photo/', include('photoApp.urls', namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Programming_Practice/Python/Web_Django/blogApp/urls.py
from django.urls import path
from blogApp.views import *

app_name = 'blogApp'

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<str:slug>', PostDV.as_view(), name='post_detail'),

    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(month_format='%m'), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(month_format='%m'), name='post_day_archive'),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),

    path('search/', SearchFormView.as_view(), name='search'),

    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
]

Programming_Practice/Python/Web_Django/blogApp/models.py
from django.db import models
from django.urls import reverse
from tagging.fields import TagField
from django.contrib.auth.models import User
from django.utils.text import slugify


# Create your models here.
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post' # default : appname_modelclassname
        ordering = ('-modify_date', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blogApp:post_detail", args=(self.slug, ))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

Programming_Practice/Python/Web_Django/blogApp/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='search word')

Programming_Practice/Python/Web_Django/blogApp/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView
from django.views.generic.dates import MonthArchiveView, DayArchiveView, TodayArchiveView
from tagging.views import TaggedObjectList
from blogApp.models import Post
from tagging.models import Tag, TaggedItem
from blogApp.forms import PostSearchForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from Web_Django.views import LoginRequiredMixin
from django.urls import reverse_lazy


# Create your views here.


class PostLV(ListView):
    model = Post
    template_name = "blogApp/post_all.html"
    context_object_name = "posts"
    paginate_by = 2


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = "modify_date"


class PostYAV(YearArchiveView):
    model = Post
    date_field = "modify_date"
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = "modify_date"


class PostDAV(DayArchiveView):
    model = Post
    date_field = "modify_date"


class PostTAV(TodayArchiveView):
    model = Post
    date_field = "modify_date"


class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'


class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blogApp/post_search.html'

    def form_valid(self, form):
        search_word = f"{self.request.POST['search_word']}"
        post_list = Post.objects.filter(Q(title__icontains=search_word) \
                                        | Q(description__icontains=search_word) \
                                        | Q(content__icontains=search_word)).distinct

        context = dict()
        context['form'] = form
        context['search_term'] = search_word
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    initial = {'slug': 'auto-filling-do-not-input'}
    #fields = ['title, 'description', 'content', 'tag']
    success_url = reverse_lazy('blogApp:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blogApp/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    success_url = reverse_lazy('blogApp:index')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blogApp:index')

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_all.html
{% extends "base.html" %}
{% block title %}Blog List{% endblock %}

{% block content %}
    <h1>Blog List</h1>
    <hr>

    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, y" }}
        <p>{{ post.description }}</p>
    {% endfor %}

    <br/>

    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">이전 페이지</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">다음 페이지</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_archive.html
{% extends "base.html" %}
{% block title %}post_archive.html{% endblock %}

{% block content %}
    <h1>Post Archive until {% now "N d, Y" %}</h1>
    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blogApp:post_year_archive' date|date:'Y' %}">
                        Year-{{ date|date:"Y" }}</a>
        </li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li> {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_archive_day.html
{% extends "base.html" %}
{% block title %}post_archive_day.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_archive_month.html
{% extends "base.html" %}
{% block title %}post_archive_month.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ month|date:"N Y" }}</h1>
        <ul>
            {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blogApp:post_day_archive' date|date:'Y' date|date:'m' date|date:'j' %}">
                    {{ date|date:"j"}}일
                </a>
            </li>
                &nbsp;
            {% endfor %}
        </ul>
        <br>

        <div>
            <ul>
                {% for post in object_list %}
                <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_archive_year.html
{% extends "base.html" %}
{% block title %}post_archive_year.html{% endblock %}

{% block content %}
    <div id="content">
       <h1>Post Archive for {{ year|date:"Y" }}</h1>
        <ul>
            {% for date in date_list %}
            <li style="display: inline;">
                <a href="{% url 'blogApp:post_month_archive' date|date:'Y' date|date:'m' %}">
                            {{ date|date:"b"}}
                        </a>
            </li>
            {% endfor %}
        </ul>
        <br>

        <div>
            <ul>
                {% for post in object_list %}
                <li>
                    {{post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_change_list.html
{% extends 'base.html' %}

{% block title %}post_change_list.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Change - {{ user }}</h1>

        <table class="change-list">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Owner</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for item in object_list %}
                    <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'blogApp:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'blogApp:delete' item.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Delete</h1>

        <form action="." method="POST">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm"/>
        </form>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_detail.html
{% extends "base.html" %}
{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div id="content">
        <h2>{{ object.title }}</h2>
        <p class="other_posts">
            {% if object.get_previous_by_modify_date %}
                <a href="{{ object.get_previous_post.get_absolute_url }}" title="View Previous Post" style="float:left">
                &lt;--이전 글 : {{ object.get_previous_post }}
                </a>
            {% endif %}
            &nbsp;
            {% if object.get_next_by_modify_date %}
                <a href="{{ object.get_next_post.get_absolute_url }}" title="View Next Post" style="float:right">
                다음 글 : {{ object.get_next_post }}--&gt;
                </a>
            {% endif %}
        </p>

        <p class="date">{{ object.modify_date|date:"Y.m.j" }}</p>
        <br/>

        <div class="body">
            {{ object.content|linebreaks }}
        </div>

        <div>
            <strong>TAGS: </strong>
            {% load tagging_tags %}
            {% tags_for_object object as tags %}
            {% for tag in tags %}
                <a href="{% url 'blogApp:tagged_object_list' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
            <a href="{% url 'blogApp:tag_cloud' %}"><i>[ TagCloud ]</i></a>
        </div>

        <br/>
        <div>
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
    </div>
{% endblock %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_form.html
{% extends 'base.html' %}

{% block title %}post_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'css/forms.css' %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Create/Update - {{ user }}</h1>

        <form action="." method="POST">{% csrf_token %}
            {% if form.errors %}
                <p class="errornote">Wrong! Please correct the error(s) below.</p>
            {% endif %}

            <p>This is creation or update form for your post.</p>

            <fieldset class="aligned">
                <div class="form-row">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-row">
                    {{ form.slug.label_tag }} {{ form.slug }}
                </div>
                <div class="form-row">
                    {{ form.description.label_tag }} {{ form.description }}
                </div>
                <div class="form-row">
                    {{ form.content.label_tag }} {{ form.content }}
                </div>
                <div class="form-row">
                    {{ form.tag.label_tag }} {{ form.tag }}
                </div>
            </fieldset>
            <div class="submit-row">
                <input type="submit" value="Submit"/>
            </div>

            <script type="text/javascript">document.getElementById('id_title').focus()</script>
        </form>
    </div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}

Programming_Practice/Python/Web_Django/blogApp/templates/blogApp/post_search.html
{% extends 'base.html' %}
{% block title %}post_search.html{% endblock %}

{% block content %}
<div id="content">
    <h1>Blog Search</h1>
        <form action="." method="POST"> {% csrf_token %}
            {{ form.as_table }}
            <input type="submit" value="Submit">
        </form>
        <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            {{ post.modify_date|date:'N d, Y' }}
            <p>{{ post.description }}</p>
        {% endfor %}

    {% elif search_term %}
        <strong><i>Search Word({{ search_term }}) is Not Found.</i></strong>
    {% endif %}
</div>
{% endblock %}

{% block footer %}
<div id="footer">
    &copy; Y.M.Kwon Django Web Programming Since 2019
</div>
{% endblock footer %}